### PR TITLE
Update dependency fill-range

### PR DESCRIPTION
**Pull request by stephenlacy**

### CODE REVIEW

**Comment by phated** [comment]
Minor version bump, I think.  I don't have permissions here.

**Comment by stephenlacy** [comment]
@jonschlinkert Can this be merged or should I close it?

**Comment by jonschlinkert** [comment]
Really sorry I missed this. I'll get it published. Thanks for the ping.

**Comment by jonschlinkert** [comment]
Patched and published as 2.0.2.  Sorry for the delay.

**Pull request merged**
